### ISSUE TITLE
floating_toolbars_on_hover.css - Firefox 70, entire site is dragged down again

### ISSUE THREAD

**Issue by Aztek92** [TinyRaindrop/Firefox-UI-customization#1]
So yeah, new "improvements" in FF70 drag entire website down along with toolbar above when hovering. I don't like it a bit ;-; Hope you still gonna maintain the style.

**Comment by TinyRaindrop** [comment]
[Fixed](https://github.com/TinyRaindrop/Firefox-UI-customization/commit/2732f730ee200125a0b48d643bf691767899e834)
